### ISSUE TITLE
need specifical request method

### ISSUE THREAD

**Issue by guihouchang** [weixinhost/yar.go#1]
调用的时候，报错need specifical request method。

**Comment by guihouchang** [comment]
经过调试，当请求的方法名超过16个字符的时，就会报出这种错误。而且只会这在特定的2台服务器上会有。

**Comment by guihouchang** [comment]
再次定位到问题是php7.2版本问题。 php 7.1, 7.0都没事

**Comment by imiskolee** [comment]
Hi: 请问你是在yar.go作为client 还是server的时候遇到的问题嘞。

**Comment by guihouchang** [comment]
> Hi: 请问你是在yar.go作为client 还是server的时候遇到的问题嘞。

作为客户端的的时候有问题
